### ISSUE TITLE
Investigate: undefined steps are not reported

### ISSUE THREAD

**Issue by shepmaster** [ci-reporter/ci_reporter_cucumber#6]
I believe I saw a case where an undefined step in a `Scenario` was not reported as a failure.

**Comment by rachelthompson** [comment]
@shepmaster and I saw undefined steps that failed, but were not reported.

**Comment by tessi** [comment]
FYI: I've attempted to fix this issue with https://github.com/ci-reporter/ci_reporter_cucumber/pull/9
